name: publish

on:
  push:
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the hello-world Docker image
      run: |
        docker build -t ghcr.io/kaizenc/scalable-io:latest -f conf/server/Dockerfile .
        docker run ghcr.io/kaizenc/scalable-io:latest
        docker push ghcr.io/kaizenc/scalable-io:latest
